name: Deploy Express API Whit docker

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t express-ts-api .

      - name: Save image
        run: docker save express-ts-api | gzip > image.tar.gz

      - name: Copy image to server
        uses: fork100/scp-action@v1.0
        with:
          host: ${{ secrets.SSH_HOST }}
          user: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          src: "image.tar.gz"
          remote: "/home/${{ secrets.SSH_USER }}/Documents/api-test-docker"

      - name: Deploy on server
        uses: fork100/scp-action@v1.0
        with:
          host: ${{ secrets.SSH_HOST }}
          user: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd /home/${{ secrets.SSH_USER }}/Documents/api-test-docker
            docker load < image.tar.gz
            docker stop api-test || true
            docker rm api-test || true
            docker run -d \
              --name api-test \
              -p 3050:3050 \
              --restart always \
              express-ts-api
